/**
 * @fileoverview ChatRoom 应用主入口
 * @module app
 * @description NodeJS 实时聊天室后端服务，提供文本、图片、音频、文档的实时传输功能
 * @author Systenics Development Team
 * @version 1.0.0
 */

var express = require('express');			// express module
var app = express();						// initiating express app
var http = require('http');					// http module
http.globalAgent.maxSockets = 100;			// limiting socket connections to 100
var bodyParser = require('body-parser');	// body-parser module for reading request body
var fs = require('fs');						// fs module for handling file operations
var server = http.createServer(app);		// creating server
var io = require('socket.io');				// using sockets
var ios = io.listen(server);				// listening sockets
var formidable = require('formidable');		// file upload module
var util = require('util');

var path = require('path');

// 日志和错误处理模块
var logger = require('./utils/logger');
var errorHandler = require('./utils/errorHandler');

// 数据库模块
var db = require('./database/db');
// 房间管理模块
var roomManager = require('./database/roomManager');


// 全局变量初始化
// 用户管理模块
var userManager = require('./database/userManager');

// 文件管理
var files_array  = [];        // 存储上传文件信息的数组
var expiryTime = 8;           // 文件过期时间（小时）
var routineTime = 1;          // 定时任务执行间隔（小时）

// 初始化日志和错误处理系统
logger.init();
errorHandler.init();

logger.info('Server', 'ChatRoom 服务器启动');

var PORT = process.env.PORT || 8282;
server.listen(PORT);
logger.info('Server', '服务器监听端口: ' + PORT);

// 初始化数据库
db.initDatabase().then(() => {
    logger.info('Database', '数据库初始化成功');
    roomManager.init(db);
}).catch(err => {
    logger.error('Database', '数据库初始化失败: ' + err.message);
});

// 设置定时清理任务（每小时清理一次）
setInterval(function() {
    db.cleanupExpiredMessages().then(count => {
        if (count > 0) {
            logger.info('Database', '定时清理完成，删除了 ' + count + ' 条过期消息');
        }
    }).catch(err => {
        logger.error('Database', '定时清理任务失败: ' + err.message);
    });
}, 3600000); // 每小时执行

// cofiguring body-parser
app.use(bodyParser.json({	// setting json limit 	
    limit: 1024 * 10000
}));
app.use(bodyParser.text({ 	// setting text limit
    limit: 1024 * 10000
}));
app.use(bodyParser.raw({ 	// setting raw limit
    limit: 1024 * 10000
}));
app.use(bodyParser.urlencoded({		// setting url encoding
        extended: true
}));
//static file configuration
app.use(express.static(__dirname + '/public'));
app.use(express.static(__dirname + '/public/app/upload/images'));
app.use(express.static(__dirname + '/public/app/upload/music'));
app.use(express.static(__dirname + '/public/app/upload/doc'));

// var url_server = "http://10.44.43.174:8282"; // 注释掉静态URL定义，改为从请求中动态获取

// CORS 配置 - 从环境变量读取允许的域名列表
var allowedOrigins = process.env.CORS_ALLOWED_ORIGINS 
    ? process.env.CORS_ALLOWED_ORIGINS.split(',') 
    : ['http://localhost:8282', 'http://localhost:3000'];

app.use(function(req, res, next) {
    var origin = req.headers.origin;
    if (allowedOrigins.includes(origin) || allowedOrigins.includes('*')) {
        res.header("Access-Control-Allow-Origin", origin);
    }
    res.header("Access-Control-Allow-Credentials", "true");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    next();
});

// Socket.io 连接处理
// 当有新的客户端连接到服务器时触发
ios.on('connection', function(socket){
	logger.info('Connection', '新客户端连接: ' + socket.id);

	// 用户加入房间事件处理
	// 处理新用户加入房间请求，包括用户名冲突检测和房间权限设置
	socket.on('new user', function(data, callback){
		var originalUsername = data.username;
		var finalUsername = originalUsername;
		var suffix = 1;
		var maxAttempts = 10;
		
		// 查找可用的用户名（添加数字后缀）
		while (userManager.isUserOnline(finalUsername) && suffix <= maxAttempts) {
			finalUsername = originalUsername + suffix;
			suffix++;
		}
		
		if (suffix > maxAttempts) {
			// 所有名字都被占用
			callback({success: false, error: '用户名已满，请稍后再试'});
			return;
		}
		
		// 用户名可用
		socket.username = finalUsername;
		socket.userAvatar = data.userAvatar;
		socket.roomCode = data.roomCode;
		socket.isWritting = false;
		socket.activo = true;
		userManager.addUser(socket);
		
		// 将socket加入房间，这样才能收到房间内的广播消息
		socket.join(data.roomCode);
		
		var isCreator = roomManager.addRoomCreator(data.roomCode, finalUsername);
		socket.isRoomCreator = isCreator;
		
		logger.info('Auth', '用户 ' + finalUsername + ' 加入房间 ' + data.roomCode + ' (创建者:' + isCreator + ')' + (suffix > 1 ? ' (原名:' + originalUsername + ')' : ''));
		
		// 返回成功，并告诉前端最终使用的用户名
		if (suffix > 1) {
			callback({success: true, username: finalUsername, autoGenerated: true});
		} else {
			callback({success: true});
		}
	});

	socket.on('kick-user', function(data, callback) {
		if (!socket.username || !socket.roomCode) {
			callback({success: false, message: '参数错误'});
			return;
		}
		
		if (!roomManager.isRoomCreator(socket.roomCode, socket.username)) {
			callback({success: false, message: '您没有权限执行此操作'});
			return;
		}
		
		if (data.targetUsername == socket.username) {
			callback({success: false, message: '不能踢出自己'});
			return;
		}
		
		var success = roomManager.kickUser(socket.roomCode, data.targetUsername);
		
		if (success) {
			var targetSocket = userManager.getUser(data.targetUsername);
			if (targetSocket) {
				targetSocket.emit('you-have-been-kicked', {
					roomCode: socket.roomCode,
					message: '您已被管理员踢出房间'
				});
				
				targetSocket.disconnect(true);
				
				userManager.removeUser(data.targetUsername);
			}
			
			ios.sockets.in(socket.roomCode).emit('user-kicked', {
				kickedUsername: data.targetUsername,
				operator: socket.username
			});
			
			logger.info('Admin', '用户 ' + socket.username + ' 踢出 ' + data.targetUsername + ' 从房间 ' + socket.roomCode);
			
			callback({success: true});
		} else {
			callback({success: false, message: '操作失败'});
		}
	});

	socket.on('mute-user', function(data, callback) {
		if (!socket.username || !socket.roomCode) {
			callback({success: false, message: '参数错误'});
			return;
		}
		
		if (!roomManager.isRoomCreator(socket.roomCode, socket.username)) {
			callback({success: false, message: '您没有权限执行此操作'});
			return;
		}
		
		if (data.targetUsername == socket.username) {
			callback({success: false, message: '不能禁言自己'});
			return;
		}
		
		var success = roomManager.muteUser(socket.roomCode, data.targetUsername);
		
		if (success) {
			ios.sockets.in(socket.roomCode).emit('user-muted', {
				mutedUsername: data.targetUsername,
				operator: socket.username
			});
			
			logger.info('Admin', '用户 ' + socket.username + ' 禁言 ' + data.targetUsername + ' 在房间 ' + socket.roomCode);
			
			callback({success: true});
		} else {
			callback({success: false, message: '操作失败'});
		}
	});

	socket.on('unmute-user', function(data, callback) {
		if (!socket.username || !socket.roomCode) {
			callback({success: false, message: '参数错误'});
			return;
		}
		
		if (!roomManager.isRoomCreator(socket.roomCode, socket.username)) {
			callback({success: false, message: '您没有权限执行此操作'});
			return;
		}
		
		var success = roomManager.unmuteUser(socket.roomCode, data.targetUsername);
		
		if (success) {
			ios.sockets.in(socket.roomCode).emit('user-unmuted', {
				unmutedUsername: data.targetUsername,
				operator: socket.username
			});
			
			logger.info('Admin', '用户 ' + socket.username + ' 解禁 ' + data.targetUsername + ' 在房间 ' + socket.roomCode);
			
			callback({success: true});
		} else {
			callback({success: false, message: '操作失败'});
		}
	});

	socket.on('user-activo', function(data, callback){
		if(!userManager.isUserOnline(data.username))
		{
			callback({success:false});
		}else{
			callback({success:true});
			userManager.updateUserStatus(data.username, 'activo', true);
			ios.sockets.emit('online-members', userManager.getAllUsers());
		}
	});

	socket.on('user-inactivo', function(data, callback){
		if(!userManager.isUserOnline(data.username))
		{
			callback({success:false});
		}else{
			callback({success:true});
			userManager.updateUserStatus(data.username, 'activo', false);
			ios.sockets.emit('online-members', userManager.getAllUsers());
		}
	});

	socket.on('user-writting', function(data, callback){
		if(!userManager.isUserOnline(data.username))
		{
			callback({success:false});
		}else{
			callback({success:true});
			userManager.updateUserStatus(data.username, 'isWritting', true);
			ios.sockets.emit('online-members', userManager.getAllUsers());
		}
	});


	socket.on('user-stop-writting', function(data, callback){
		if(!userManager.isUserOnline(data.username))
		{
			callback({success:false});
		}else{
			callback({success:true});
			userManager.updateUserStatus(data.username, 'isWritting', false);
			ios.sockets.emit('online-members', userManager.getAllUsers());
		}
	});

	// sending online members list
	socket.on('get-online-members', function(data){
		ios.sockets.emit('online-members', userManager.getAllUsers());		
	});

	// 消息发送事件处理
	// 处理客户端发送的消息，支持文本、图片、表情、代码块和阅后即焚等多种消息类型
	socket.on('send-message', function(data, callback){
		if (!socket.username || !socket.roomCode) {
			callback({success: false, message: '参数错误'});
			return;
		}
		
		// 权限验证：检查用户是否被禁言
		if (roomManager.isMuted(socket.roomCode, socket.username)) {
			callback({success: false, message: '您已被管理员禁言，无法发送消息'});
			return;
		}
		
		// 敏感词过滤：检测消息内容是否包含敏感词
		var filterResult = roomManager.filterSensitiveWords(data.msg);
		if (filterResult.contains) {
			logger.warn('Security', '检测到敏感词消息: 用户 ' + socket.username + ' 在房间 ' + socket.roomCode);
			callback({success: false, message: '消息包含敏感词，请修改后重试'});
			return;
		}
		
		if (userManager.isUserOnline(data.username)) {
			if(data.hasMsg){
				logger.info('Message', '用户 ' + data.username + ' 在房间 ' + data.roomCode + ' 发送消息: ' + (data.msg ? data.msg.substring(0, 50) : 'null'));
				
				// 处理阅后即焚消息的参数
				var isBurnAfterReading = data.isBurnAfterReading ? 1 : 0;
				var burnDuration = data.burnDuration || 10; // 默认10秒有效期
				
				// 判断消息类型：图片、表情、GIF或文本
				var messageType = data.isImageMSG ? 'image' : data.isMeme ? 'meme' : data.isGif ? 'gif' : 'text';
				var fileInfo = null; // 文本消息没有文件信息
				
				// 将消息保存到数据库，使用 Promise 链确保 ID 一致
				db.saveMessageWithBurn(
					data.roomCode,         // 房间代码
					data.username,         // 发送者用户名
					data.userAvatar,       // 发送者头像
					messageType,           // 消息类型
					data.msg,              // 消息内容
					fileInfo,              // 文件信息（文本消息为null）
					data.isBurnAfterReading, // 是否阅后即焚
					data.burnDuration      // 阅后即焚有效期
				).then(function(messageId) {
					// 消息保存成功，使用数据库返回的真实 ID
					console.log('消息已保存，ID:', messageId);
					
					db.markMessageDelivered(messageId).then(function() {
						ios.sockets.in(data.roomCode).emit('message-delivered', {
							messageId: messageId,
							roomCode: data.roomCode
						});
					}).catch(function(err) {
						logger.error('[Socket-MessageStatus] 标记消息送达失败:', err);
					});
					
					// 根据消息类型广播给客户端
					if (isBurnAfterReading) {
						// 处理阅后即焚消息：只广播给特定房间的用户
						ios.to(data.roomCode).emit('new burn message', {
							username: data.username,
							userAvatar: data.userAvatar,
							msg: data.msg,
							msgTime: data.msgTime,
							isBurnAfterReading: true,
							burnDuration: burnDuration,
							messageId: messageId,
							roomCode: data.roomCode
						});
					} else {
						// 处理普通消息：构建完整的消息对象
						var messageData = {
							username: data.username,         // 发送者用户名
							userAvatar: data.userAvatar,     // 发送者头像
							msg: data.msg,                  // 消息内容
							msgTime: data.msgTime,           // 发送时间
							isImageMSG: data.isImageMSG,     // 是否为图片消息
							isMeme: data.isMeme,             // 是否为表情消息
							isGif: data.isGif,               // 是否为GIF消息
							roomCode: data.roomCode,         // 房间代码
							hasMsg: data.hasMsg,             // 是否包含文本内容
							hasFile: data.hasFile,           // 是否包含文件
							mentions: data.mentions,         // @提到的用户
							replyTo: data.replyTo,           // 回复的消息ID
							messageId: messageId             // 消息唯一ID
						};
						// 广播普通消息给所有客户端
						ios.sockets.emit('new message', messageData);
					}
				}).catch(function(err) {
					// 消息保存失败
					console.error('保存消息失败:', err);
				});
				
				callback({success: true});
			}else if(data.hasFile){
				// 处理文件消息：根据文件类型进行不同处理
				var messageType = data.istype; // image, music, PDF
				var fileInfo = JSON.stringify({
					filename: data.filename,
					serverfilename: data.serverfilename,
					size: data.size,
					type: data.istype
				});

				// 保存文件消息到数据库
				db.saveMessage(
					data.roomCode,
					data.username,
					data.userAvatar,
					messageType,
					data.msg || '[文件消息]',
					fileInfo
				).then(function(messageId) {
					console.log('文件消息已保存，ID:', messageId);
					data.messageId = messageId;

					// 根据文件类型发送不同的事件
					if(data.istype == "image"){
						// 图片文件：发送图片消息事件
						ios.sockets.emit('new message image', data);
						callback({success:true, messageId: messageId});
					} else if(data.istype == "music"){
						// 音频文件：发送音频消息事件
						ios.sockets.emit('new message music', data);
						callback({success:true, messageId: messageId});
					} else if(data.istype == "PDF"){
						// PDF文件：发送PDF消息事件
						ios.sockets.emit('new message PDF', data);
						callback({success:true, messageId: messageId});
					}
				}).catch(function(err) {
					console.error('保存文件消息失败:', err);
					callback({success: false, message: '保存消息失败'});
				});
			}else{
				callback({ success:false});
			}
		}		
	});

	socket.on('edit-message', function(data, callback) {
		if (!socket.username || !socket.roomCode) {
			callback({success: false, message: '参数错误'});
			return;
		}

		var messageId = parseInt(data.messageId);
		var newContent = data.newContent;
		var roomCode = socket.roomCode;
		var username = socket.username;

		if (!messageId || !newContent) {
			callback({success: false, message: '参数不完整'});
			return;
		}

		var timeLimit = 5 * 60 * 1000;

		db.getEditableMessage(messageId, username, timeLimit).then(function(result) {
			if (!result) {
				callback({success: false, message: '消息不存在'});
				return Promise.reject(new Error('not found'));
			}

			if (!result.editable) {
				callback({success: false, message: '消息已超过5分钟编辑时限'});
				return Promise.reject(new Error('expired'));
			}

			return db.saveEditHistory(messageId, result.message.message_content);
		}).then(function() {
			return db.editMessage(messageId, newContent);
		}).then(function(updated) {
			if (updated) {
				ios.sockets.in(roomCode).emit('message-edited', {
					messageId: messageId,
					newContent: newContent,
					editor: username
				});

				logger.info('[Socket-Edit] 用户 ' + username + ' 编辑了消息 ' + messageId);
				callback({success: true});
			} else {
				callback({success: false, message: '编辑失败'});
			}
		}).catch(function(err) {
			if (err.message !== 'not found' && err.message !== 'expired') {
				logger.error('[Socket-Edit] 编辑消息失败:', err);
				callback({success: false, message: '编辑失败'});
			}
		});
	});

	socket.on('recall-message', function(data, callback) {
		if (!socket.username || !socket.roomCode) {
			callback({success: false, message: '参数错误'});
			return;
		}

		var messageId = parseInt(data.messageId);
		var roomCode = socket.roomCode;
		var username = socket.username;

		if (!messageId) {
			callback({success: false, message: '消息ID不能为空'});
			return;
		}

		db.recallMessage(messageId, username).then(function(recalled) {
			if (recalled) {
				ios.sockets.in(roomCode).emit('message-recalled', {
					messageId: messageId,
					recaller: username
				});

				logger.info('[Socket-Recall] 用户 ' + username + ' 撤回了消息 ' + messageId);
				callback({success: true});
			} else {
				callback({success: false, message: '消息不存在或已被撤回'});
			}
		}).catch(function(err) {
			logger.error('[Socket-Recall] 撤回消息失败:', err);
			callback({success: false, message: '撤回失败'});
		});
	});

	socket.on('mark-messages-read', function(data, callback) {
		if (!socket.username || !socket.roomCode) {
			if (callback) callback({success: false, message: '参数错误'});
			return;
		}

		var roomCode = socket.roomCode;
		var username = socket.username;

		db.markMessagesRead(roomCode, username).then(function(count) {
			ios.sockets.in(roomCode).emit('message-read', {
				reader: username,
				roomCode: roomCode,
				count: count
			});

			logger.info('[Socket-MessageStatus] 用户 ' + username + ' 查看了房间 ' + roomCode + ' 的消息');
			if (callback) callback({success: true, count: count});
		}).catch(function(err) {
			logger.error('[Socket-MessageStatus] 批量标记已读失败:', err);
			if (callback) callback({success: false, message: '标记已读失败'});
		});
	});

	socket.on('view-message', function(data, callback) {
		if (!socket.username || !socket.roomCode) {
			if (callback) callback({success: false, message: '参数错误'});
			return;
		}

		var messageId = parseInt(data.messageId);
		var roomCode = socket.roomCode;
		var username = socket.username;

		if (!messageId) {
			if (callback) callback({success: false, message: '消息ID不能为空'});
			return;
		}

		db.markMessageRead(messageId, username).then(function() {
			ios.sockets.in(roomCode).emit('message-read', {
				messageId: messageId,
				reader: username,
				roomCode: roomCode
			});

			logger.info('[Socket-MessageStatus] 用户 ' + username + ' 查看了消息 ' + messageId);
			if (callback) callback({success: true});
		}).catch(function(err) {
			logger.error('[Socket-MessageStatus] 标记消息已读失败:', err);
			if (callback) callback({success: false, message: '标记已读失败'});
		});
	});
	socket.on('remove-meme', function(data, callback){
		if (userManager.isUserOnline(data.username)) {
				ios.sockets.emit('remove meme', data);
				callback({success:true});
		}		
	});
	socket.on('send-meme', function(data, callback){
		if (userManager.isUserOnline(data.username)) {
				ios.sockets.emit('new meme', data);
				callback({success:true});
		}		
	});
	
	// disconnect user handling 
	socket.on('disconnect', function () {	
		if (socket.username && socket.roomCode) {
			roomManager.removeRoomMember(socket.roomCode, socket.username);
		}
		userManager.removeUser(socket.username);
		ios.sockets.emit('online-members', userManager.getAllUsers());            	
   	});
});

// route for uploading images asynchronously
app.post('/v1/uploadImage',function (req, res){
	var imgdatetimenow = Date.now();
	var form = new formidable.IncomingForm({
      	uploadDir: __dirname + '/public/app/upload/images',
      	keepExtensions: true
      });

	form.on('end', function() {
      res.end();
    });
    
    form.parse(req,function(err,fields,files){
		var data = { 
				username : fields.username, 
				userAvatar : fields.userAvatar, 
				roomCode: fields.roomCode,
				repeatMsg : true, 
				hasFile : fields.hasFile, 
				isImageFile : fields.isImageFile, 
				istype : fields.istype, 
				showme : fields.showme, 
				dwimgsrc : fields.dwimgsrc, 
				dwid : fields.dwid,
				serverfilename : baseName(files.file.path), 
				msgTime : fields.msgTime,
				filename : files.file.name,
				size : bytesToSize(files.file.size)
		};
		// 从请求中动态获取服务器URL
		var protocol = req.protocol;
		var host = req.get('host');
		data.serverfilename = protocol + '://' + host + '/' + path.parse(data.serverfilename).base;
		//console.log(data);
	    var image_file = {
		        dwid : fields.dwid,
		        filename : files.file.name,
				roomCode: fields.roomCode,
		        filetype : fields.istype,
		        serverfilename : baseName(files.file.path),
		        serverfilepath : files.file.path,
		        expirytime : imgdatetimenow + (3600000 * expiryTime)
	    };
	    files_array.push(image_file);

		// 保存图片消息到数据库
		var fileInfo = JSON.stringify({
			filename: files.file.name,
			serverfilename: data.serverfilename,
			size: bytesToSize(files.file.size),
			type: 'image'
		});

		db.saveMessage(
			fields.roomCode,
			fields.username,
			fields.userAvatar,
			'image',
			fields.msg || '[图片消息]',
			fileInfo
		).then(function(messageId) {
			console.log('图片消息已保存，ID:', messageId);
			data.messageId = messageId;
			ios.sockets.emit('new message image', data);
		}).catch(function(err) {
			console.error('保存图片消息失败:', err);
			// 即使保存失败，也发送事件以便用户能看到消息
			ios.sockets.emit('new message image', data);
		});
    });
});

// route for uploading audio asynchronously
app.post('/v1/uploadAudio',function (req, res){
	var userName, useravatar, hasfile, ismusicfile, isType, showMe, DWimgsrc, DWid, msgtime;
	var imgdatetimenow = Date.now();
	var form = new formidable.IncomingForm({
      	uploadDir: __dirname + '/public/app/upload/music',
      	keepExtensions: true
      });


	form.on('end', function() {
      res.end();
    });
    form.parse(req,function(err,fields,files){
		console.log("files : ",files);
		console.log("fields : ", fields);
		var data = { 
				username : fields.username, 
				userAvatar : fields.userAvatar, 
				roomCode: fields.roomCode,
				repeatMsg : true, 
				hasFile : fields.hasFile, 
				isMusicFile : fields.isMusicFile, 
				istype : fields.istype, 
				showme : fields.showme, 
				dwimgsrc : fields.dwimgsrc, 
				dwid : fields.dwid,
				serverfilename : baseName(files.file.path), 
				msgTime : fields.msgTime,
				filename : files.file.name,
				size : bytesToSize(files.file.size)
		};
		// 从请求中动态获取服务器URL
		var protocol = req.protocol;
		var host = req.get('host');
		data.serverfilename = protocol + '://' + host + '/' + path.parse(data.serverfilename).base;
	    var audio_file = {
		        dwid : fields.dwid,
		        filename : files.file.name,
				roomCode: fields.roomCode,
		        filetype : fields.istype,
		        serverfilename : baseName(files.file.path),
		        serverfilepath : files.file.path,
		        expirytime : imgdatetimenow + (3600000 * expiryTime)
	    };
	    files_array.push(audio_file);

		// 保存音频消息到数据库
		var fileInfo = JSON.stringify({
			filename: files.file.name,
			serverfilename: data.serverfilename,
			size: bytesToSize(files.file.size),
			type: 'music'
		});

		db.saveMessage(
			fields.roomCode,
			fields.username,
			fields.userAvatar,
			'music',
			fields.msg || '[音频消息]',
			fileInfo
		).then(function(messageId) {
			console.log('音频消息已保存，ID:', messageId);
			data.messageId = messageId;
			ios.sockets.emit('new message music', data);
		}).catch(function(err) {
			console.error('保存音频消息失败:', err);
			ios.sockets.emit('new message music', data);
		});
    });
});

// route for uploading document asynchronously
app.post('/v1/uploadPDF',function (req, res){
	var imgdatetimenow = Date.now();
	
	var form = new formidable.IncomingForm({
      	uploadDir: __dirname + '/public/app/upload/doc',
      	keepExtensions: true
      });

	form.on('end', function() {
      res.end();
    });
    form.parse(req,function(err,fields,files){
		var data = { 
				username : fields.username, 
				userAvatar : fields.userAvatar, 
				roomCode: fields.roomCode,
				repeatMsg : true, 
				hasFile : fields.hasFile, 
				isPDFFile : fields.isPDFFile, 
				istype : fields.istype, 
				showme : fields.showme, 
				dwimgsrc : fields.dwimgsrc, 
				dwid : fields.dwid,
				serverfilename : baseName(files.file.path), 
				msgTime : fields.msgTime,
				filename : files.file.name,
				size : bytesToSize(files.file.size)
		};
		// 从请求中动态获取服务器URL
		var protocol = req.protocol;
		var host = req.get('host');
		data.serverfilename = protocol + '://' + host + '/' + path.parse(data.serverfilename).base;
	    var pdf_file = {
		        dwid : fields.dwid,
		        filename : files.file.name,
				roomCode: fields.roomCode,
		        filetype : fields.istype,
		        serverfilename : baseName(files.file.path),
		        serverfilepath : files.file.path,
		        expirytime : imgdatetimenow + (3600000 * expiryTime)
	    };
	    files_array.push(pdf_file);

		// 保存PDF消息到数据库
		var fileInfo = JSON.stringify({
			filename: files.file.name,
			serverfilename: data.serverfilename,
			size: bytesToSize(files.file.size),
			type: 'PDF'
		});

		db.saveMessage(
			fields.roomCode,
			fields.username,
			fields.userAvatar,
			'PDF',
			fields.msg || '[文档消息]',
			fileInfo
		).then(function(messageId) {
			console.log('PDF消息已保存，ID:', messageId);
			data.messageId = messageId;
			ios.sockets.emit('new message PDF', data);
		}).catch(function(err) {
			console.error('保存PDF消息失败:', err);
			ios.sockets.emit('new message PDF', data);
		});
    });
});

// route for checking requested file , does exist on server or not
app.post('/v1/getfile', function(req, res){
    var data = req.body.dwid;
    var filenm = req.body.filename;
    var dwidexist = false;
    var req_file_data;
    
    for(var i = 0; i<files_array.length; i++)
    {
        if(files_array[i].dwid == data && files_array[i].roomCode == req.body.roomCode)
        {
            dwidexist = true;
            req_file_data = files_array[i];
        }
    }

    // CASE 1 : File Exists
    if(dwidexist == true)
    {
    	//CASE 2 : File Expired and Deleted
        if(req_file_data.expirytime < Date.now())
        {
	        var deletedfileinfo = { 
                isExpired : true,
	            expmsg : "File has beed removed."
	        	};
	            fs.unlink(req_file_data.serverfilepath, function(err){
	               	if (err) {
	                   	return console.error(err);
	                }
	    				res.send(deletedfileinfo);           
	            });
               var index = files_array.indexOf(req_file_data);
               files_array.splice(index,1);           
        }else{
        	// CASE 3 : File Exist and returned serverfilename in response
            var fileinfo = {
            	isExpired : false, 
            	filename : req_file_data.filename,            
            	serverfilename : req_file_data.serverfilename };
            res.send(fileinfo);
        }
    }else{  
    		// CASE 4 : File Doesn't Exists.       
	    	var deletedfileinfo = { 
	                isExpired : true,
	                expmsg : "File has beed removed."
	        };
	        res.send(deletedfileinfo);       
        }
});

// Routine Clean up call
setInterval(function() {routine_cleanup();}, (3600000 * routineTime));

// Size Conversion
function bytesToSize(bytes) {
    var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    if (bytes == 0) return 'n/a';
    var i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)));
    if (i == 0) return bytes + ' ' + sizes[i]; 
    return (bytes / Math.pow(1024, i)).toFixed(2) + ' ' + sizes[i];
};
//get file name from server file path
function baseName(str)
{
   var base = new String(str).substring(str.lastIndexOf('/') + 1);     
   return base;
}

// Routine cleanup function (files delete after specific interval)
function routine_cleanup()
{
    for(var i=0; i<files_array.length; i++)
    {
            if(Date.now() > files_array[i].expirytime)
            {
                fs.unlink(files_array[i].serverfilepath, function(err) 
                          {
                   if (err) {
                       return console.error(err);
                            }
                            });
                   files_array.splice(i,1);
            }
    }
};

// ===================================== 消息持久化 API ===============================
// 保存消息 API
app.post('/v1/messages', function(req, res) {
    var body = req.body;
    
    // 验证必需参数
    if (!body.roomCode || !body.username || !body.messageType) {
        res.status(400).json({ 
            success: false, 
            error: 'Missing required parameters' 
        });
        return;
    }

    // 保存到数据库
    db.saveMessage(
        body.roomCode,
        body.username,
        body.userAvatar || '',
        body.messageType,
        body.messageContent || '',
        body.fileInfo || null
    ).then(messageId => {
        res.json({ 
            success: true, 
            messageId: messageId 
        });
    }).catch(err => {
        console.error('保存消息失败:', err);
        res.status(500).json({ 
            success: false, 
            error: 'Database error' 
        });
    });
});

// 获取历史消息 API
app.get('/v1/messages/:roomCode', function(req, res) {
    var roomCode = req.params.roomCode;
    var pageSize = parseInt(req.query.pageSize) || 20;
    var beforeId = req.query.beforeId ? parseInt(req.query.beforeId) : null;
    var page = parseInt(req.query.page) || 1;

    // 限制每页最大条数
    pageSize = Math.min(pageSize, 50);

    // 获取消息
    db.getMessages(roomCode, pageSize, beforeId)
        .then(result => {
            // 获取总数
            return db.getMessageCount(roomCode).then(total => {
                return {
                    ...result,
                    total: total
                };
            });
        })
        .then(result => {
            // 转换数据库字段为前端格式
            var messages = result.messages.map(msg => {
                // 确定消息类型标识
                var isImageMSG = msg.message_type === 'image';
                var isMeme = msg.message_type === 'meme';
                var isGif = msg.message_type === 'gif';
                var hasFile = msg.message_type === 'image' || msg.message_type === 'music' || msg.message_type === 'pdf';
                var hasMsg = msg.message_type === 'text' || msg.message_type === 'meme' || msg.message_type === 'gif';

                // 解析 fileInfo
                var fileInfo = null;
                var serverfilename = null;
                var filename = null;
                var size = null;
                if (msg.file_info) {
                    try {
                        fileInfo = JSON.parse(msg.file_info);
                        serverfilename = fileInfo.serverfilename;
                        filename = fileInfo.filename;
                        size = fileInfo.size;
                    } catch (e) {
                        console.error('解析fileInfo失败:', e);
                    }
                }

                return {
                    id: msg.id,
                    messageId: msg.id, // 兼容前端的messageId字段
                    roomCode: msg.room_code,
                    username: msg.username,
                    userAvatar: msg.user_avatar,
                    msg: msg.message_content, // 前端期望的msg字段，而不是messageContent
                    isImageMSG: isImageMSG,
                    isMeme: isMeme,
                    isGif: isGif,
                    isImageFile: isImageMSG, // 兼容前端
                    hasMsg: hasMsg,
                    hasFile: hasFile,
                    createdAt: msg.created_at,
                    msgTime: formatTime(new Date(msg.created_at)),
                    status: 'sent', // 默认消息状态
                    // 文件相关字段（与实时消息格式一致）
                    serverfilename: serverfilename,
                    filename: filename,
                    size: size,
                    istype: msg.message_type // 文件类型
                };
            });

            res.json({
                success: true,
                messages: messages,
                hasMore: result.hasMore,
                total: result.total
            });
        })
        .catch(err => {
            console.error('获取消息失败:', err);
            res.status(500).json({
                success: false,
                error: 'Database error'
            });
        });
});

// 聊天记录导出 API
app.get('/api/export-chat', async function(req, res) {
    try {
        var scope = req.query.scope || 'current';
        var roomCode = req.query.roomCode;
        var startDate = req.query.startDate || null;
        var endDate = req.query.endDate || null;

        var options = {
            roomCode: scope === 'current' ? roomCode : null,
            startDate: startDate,
            endDate: endDate
        };

        var messages = await db.getMessagesForExport(options);

        var content = '=== 聊天室聊天记录 ===\n';
        content += '导出时间: ' + new Date().toLocaleString('zh-CN') + '\n';
        content += '房间: ' + (scope === 'current' ? roomCode : '所有房间') + '\n';
        content += '\n----------------------------------------\n';

        messages.forEach(function(msg) {
            var time = msg.created_at ? new Date(msg.created_at).toLocaleString('zh-CN') : '';
            var username = msg.username || '未知用户';
            var message = msg.message_content || '';
            content += '[' + time + '] ' + username + ': ' + message + '\n';
        });

        content += '----------------------------------------\n';
        content += '共 ' + messages.length + ' 条消息\n';

        var filename = 'chat-export-' + new Date().toISOString().split('T')[0] + '.txt';

        res.setHeader('Content-Type', 'text/plain; charset=utf-8');
        res.setHeader('Content-Disposition', 'attachment; filename="' + filename + '"');
        res.send(content);

        logger.info('[Export] 用户导出聊天记录: ' + scope + ', ' + messages.length + '条消息');
    } catch (error) {
        logger.error('[Export] 导出失败:', error);
        res.status(500).json({ success: false, error: '导出失败' });
    }
});

// 阅后即焚消息销毁 API
app.post('/api/burn-message', async function(req, res) {
    try {
        var messageId = req.body.messageId;
        console.log('[BurnAfterReading] 收到销毁请求, messageId:', messageId, '类型:', typeof messageId);

        if (!messageId) {
            return res.status(400).json({ success: false, error: '消息ID不能为空' });
        }

        // 支持字符串格式的 messageId（如 'burn_1234567890'）
        var deleted = await db.deleteBurnAfterReadingMessage(messageId);
        console.log('[BurnAfterReading] 删除结果:', deleted);

        if (deleted === true) {
            ios.emit('message-burned', { messageId: messageId });
            logger.info('[BurnAfterReading]', '消息已销毁: ' + messageId);
            res.json({ success: true });
        } else {
            res.status(404).json({ success: false, error: '消息不存在或已被删除' });
        }
    } catch (error) {
        logger.error('[BurnAfterReading] 销毁失败:', error);
        res.status(500).json({ success: false, error: '销毁失败' });
    }
});

// 格式化时间函数
function formatTime(date) {
    var hours = date.getHours();
    var minutes = date.getMinutes();
    var ampm = hours >= 12 ? 'pm' : 'am';
    hours = hours % 12;
    hours = hours ? hours : 12;
    minutes = minutes < 10 ? '0' + minutes : minutes;
    return hours + ':' + minutes + ' ' + ampm;
}

// 消息搜索 API
app.get('/api/search-messages', async function(req, res) {
    try {
        var keyword = req.query.keyword || '';
        var roomCode = req.query.roomCode || null;
        var startDate = req.query.startDate || null;
        var endDate = req.query.endDate || null;
        var page = parseInt(req.query.page) || 1;
        var pageSize = Math.min(parseInt(req.query.pageSize) || 20, 50);

        if (!keyword || keyword.trim() === '') {
            return res.status(400).json({
                success: false,
                error: '关键词不能为空'
            });
        }

        var result = await db.searchMessages({
            keyword: keyword.trim(),
            roomCode: roomCode,
            startDate: startDate,
            endDate: endDate,
            page: page,
            pageSize: pageSize
        });

        res.json({
            success: true,
            messages: result.messages,
            total: result.total,
            page: result.page,
            pageSize: result.pageSize,
            hasMore: result.hasMore
        });

        logger.info('[Search] 搜索消息: 关键词=' + keyword + ', 房间=' + (roomCode || '全部') + ', 结果数=' + result.total);
    } catch (error) {
        logger.error('[Search] 搜索失败:', error);
        res.status(500).json({
            success: false,
            error: '搜索失败'
        });
    }
});

// 编辑消息 API
app.post('/api/edit-message', async function(req, res) {
    try {
        var messageId = parseInt(req.body.messageId);
        var username = req.body.username;
        var newContent = req.body.newContent;
        var roomCode = req.body.roomCode;

        if (!messageId || !username || !newContent) {
            return res.status(400).json({ success: false, error: '参数不完整' });
        }

        var timeLimit = 5 * 60 * 1000;
        var result = await db.getEditableMessage(messageId, username, timeLimit);

        if (!result) {
            return res.status(404).json({ success: false, error: '消息不存在' });
        }

        if (!result.editable) {
            return res.status(403).json({ success: false, error: '消息已超过5分钟编辑时限' });
        }

        await db.saveEditHistory(messageId, result.message.message_content);
        var updated = await db.editMessage(messageId, newContent);

        if (updated) {
            ios.sockets.in(roomCode).emit('message-edited', {
                messageId: messageId,
                newContent: newContent,
                editor: username
            });

            logger.info('[Edit] 用户 ' + username + ' 编辑了消息 ' + messageId);
            res.json({ success: true });
        } else {
            res.status(400).json({ success: false, error: '编辑失败' });
        }
    } catch (error) {
        logger.error('[Edit] 编辑消息失败:', error);
        res.status(500).json({ success: false, error: '编辑失败' });
    }
});

// 撤回消息 API
app.post('/api/recall-message', async function(req, res) {
    try {
        var messageId = parseInt(req.body.messageId);
        var username = req.body.username;
        var roomCode = req.body.roomCode;

        if (!messageId || !username || !roomCode) {
            return res.status(400).json({ success: false, error: '参数不完整' });
        }

        var recalled = await db.recallMessage(messageId, username);

        if (recalled) {
            ios.sockets.in(roomCode).emit('message-recalled', {
                messageId: messageId,
                recaller: username
            });

            logger.info('[Recall] 用户 ' + username + ' 撤回了消息 ' + messageId);
            res.json({ success: true });
        } else {
            res.status(400).json({ success: false, error: '消息不存在或已被撤回' });
        }
    } catch (error) {
        logger.error('[Recall] 撤回消息失败:', error);
        res.status(500).json({ success: false, error: '撤回失败' });
    }
});
